# Generated by Django 4.2.11 on 2024-07-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0005_alter_user_emp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetails",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="user_auth.comments",
            ),
        ),
        migrations.AlterField(
            model_name="bankdetails",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bankdetails",
            name="pincode",
            field=models.CharField(max_length=6),
        ),
    ]
