# Generated by Django 4.2.11 on 2024-04-20 16:33

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_id',
            field=models.CharField(default=utils.generate_leadID, max_length=255, unique=True),
        ),
    ]
