# Generated by Django 4.2.11 on 2024-04-29 17:41

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='agent_code',
            field=models.CharField(default=utils.generate_agent_code, max_length=255, null=True),
        ),
    ]
