# Generated by Django 4.2.11 on 2024-04-21 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cif_id', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('case_tag', models.CharField(max_length=255)),
                ('customer_type', models.CharField(max_length=255)),
                ('agent_code', models.CharField(max_length=255)),
                ('branch_code', models.CharField(max_length=255)),
                ('load_amount', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('customer_segment', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('source_of_income', models.CharField(max_length=255)),
                ('monthly_income', models.IntegerField()),
                ('monthly_family_income', models.IntegerField()),
                ('questions', models.BooleanField()),
                ('current_address', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('kyc_id', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant', to='applicants.applicants')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
