# Generated by Django 4.2.11 on 2024-04-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='current_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='customer_segment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='customer_type',
            field=models.CharField(default='Unknow', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='load_amount',
            field=models.CharField(default=1000, max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthly_family_income',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthly_income',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='occupation',
            field=models.CharField(default='Worker', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='permanent_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='questions',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='source',
            field=models.CharField(default='website', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='source_of_income',
            field=models.CharField(default='Business', max_length=255, null=True),
        ),
    ]
