# Generated by Django 4.2.11 on 2024-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_customer_segment_customerdetails_agriculturalland_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='age',
            field=models.CharField(max_length=255),
        ),
    ]
