# Generated by Django 4.2.11 on 2024-04-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customerdetails_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='earningsFromAgriculturalLand',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthlyFamilyIncome',
            field=models.CharField(default=10000),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthlyIncome',
            field=models.CharField(default=10000),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='numberOfDependents',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='valueOfAgriculturalLand',
            field=models.CharField(null=True),
        ),
    ]
