# Generated by Django 4.2.11 on 2024-04-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customerdetails_dateofbirth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customerdetails',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
