# Generated by Django 4.2.11 on 2024-04-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_applicants_application_id'),
        ('customer', '0007_rename_firstname_customerdetails_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='load_amount',
            new_name='industry',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='occupation',
            field=models.CharField(default='Worker', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant', to='applicants.applicants'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='customerSegment',
            field=models.CharField(choices=[('self_employee', 'Self Employment'), ('professional', 'Professional')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='earningsFromAgriculturalLand',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthlyFamilyIncome',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthlyIncome',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='numberOfDependents',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='profile_photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('out_source', 'Out_Source')], default='website', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='title',
            field=models.CharField(choices=[('miss', 'Miss'), ('ms.', 'Ms.'), ('mrs', 'Mrs.'), ('mr.', 'Mr.')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='valueOfAgriculturalLand',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
