# Generated by Django 4.2.11 on 2024-04-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_load_amount_customerdetails_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='earningsFromAgriculturalLand',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthlyFamilyIncome',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthlyIncome',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='valueOfAgriculturalLand',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
