# Generated by Django 4.2.11 on 2024-05-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('customer', '0013_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='agriculturalLand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_auth.comments'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='current_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='customerSegment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='earningsFromAgriculturalLand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='educationQualification',
            field=models.CharField(blank=True, null=True, verbose_name=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthlyFamilyIncome',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='monthlyIncome',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='numberOfDependents',
            field=models.CharField(default=1, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='occupation',
            field=models.CharField(blank=True, default='Worker', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='residenceOwnership',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('out_source', 'Out_Source')], default='website', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='sourceOfIncome',
            field=models.CharField(blank=True, default='Business', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='title',
            field=models.CharField(blank=True, choices=[('miss', 'Miss'), ('ms.', 'Ms.'), ('mrs', 'Mrs.'), ('mr.', 'Mr.')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='valueOfAgriculturalLand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
