# Generated by Django 4.2.11 on 2024-05-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_customerdetails_agriculturalland_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='numberOfDependents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
