# Generated by Django 4.2.11 on 2024-05-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_customerdetails_numberofdependents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='role',
            field=models.CharField(blank=True, default='applicant', max_length=255, null=True),
        ),
    ]
