# Generated by Django 4.2.11 on 2024-05-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_customerdetails_current_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
