# Generated by Django 4.2.11 on 2024-06-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0018_alter_customerdetails_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdetails",
            name="lastName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
