# Generated by Django 4.2.11 on 2024-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0019_alter_customerdetails_lastname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdetails",
            name="role",
            field=models.CharField(
                choices=[("Applicant", "APPLICANT"), ("Co-Applicant", "CO-APPLICANT")],
                default="applicant",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
