# Generated by Django 4.2.11 on 2024-06-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0021_alter_customerdetails_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdetails",
            name="educationQualification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customerdetails",
            name="profile_photo",
            field=models.CharField(blank=True, null=True),
        ),
    ]
