# Generated by Django 4.2.11 on 2024-08-11 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0009_alter_documentsupload_file"),
        ("customer", "0023_alter_customerdetails_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerdetails",
            name="current_address",
        ),
        migrations.RemoveField(
            model_name="customerdetails",
            name="permanent_address",
        ),
        migrations.CreateModel(
            name="CustomerKYCDetails",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aadhaar_num", models.CharField(max_length=12)),
                ("aadhaar_file", models.CharField()),
                ("pan_num", models.CharField(max_length=10)),
                ("pan_file", models.CharField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.customerdetails",
                    ),
                ),
                (
                    "kyc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="kyc.kycdetails",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
