# Generated by Django 4.2.11 on 2024-08-11 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0024_remove_customerdetails_current_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerkycdetails",
            name="kyc",
        ),
    ]
