# Generated by Django 4.2.11 on 2024-08-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0025_remove_customerkycdetails_kyc"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerkycdetails",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
