# Generated by Django 4.2.11 on 2024-04-21 13:31

from django.db import migrations, models
import utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_id', models.CharField(default=utils.generate_applicationID, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
