# Generated by Django 4.2.11 on 2024-04-21 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phonepay', '0001_initial'),
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_id', models.CharField(max_length=255)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.leads')),
                ('paymentedetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentdetail', to='phonepay.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
