# Generated by Django 4.2.11 on 2024-04-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonepay', '0001_initial'),
        ('applicants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='paymentedetails',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paymentdetail', to='phonepay.payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicants',
            name='application_id',
            field=models.CharField(max_length=255),
        ),
    ]
