# Generated by Django 4.2.11 on 2024-04-23 03:37

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_applicants_paymentedetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='application_id',
            field=models.CharField(default=utils.generate_applicationID, max_length=255),
        ),
    ]
