# Generated by Django 4.2.11 on 2024-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_applicants_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('approved', 'Approved')], max_length=200, null=True),
        ),
    ]
