# Generated by Django 4.2.11 on 2024-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_applicants_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('approved', 'Approved')], default='in_progress', max_length=200),
        ),
    ]
