# Generated by Django 4.2.11 on 2024-04-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
        ('applicants', '0007_applicants_comment_applicants_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='lead',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.leads'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='status',
            field=models.CharField(choices=[('ro_phase', 'RO Phase'), ('do_phase', 'DO phase'), ('md_phase', 'MD Phase'), ('bm_phase', 'BM phase'), ('technical_officer', 'Technical Officer'), ('cluster', 'Cluster')], default='ro_phase', max_length=200),
        ),
    ]
