# Generated by Django 4.2.11 on 2024-05-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_alter_applicants_lead_alter_applicants_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='status',
            field=models.CharField(choices=[('ro_phase', 'Review Phase'), ('ap_phase', 'Approval Phase'), ('rej_phase', 'Rejection Phase')], default='ro_phase', max_length=200),
        ),
    ]
