# Generated by Django 4.2.11 on 2024-05-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_leads_agent_code'),
        ('applicants', '0010_audittrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.leads'),
        ),
    ]
