# Generated by Django 4.2.11 on 2024-05-18 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applicants", "0011_alter_applicants_description_alter_applicants_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicants",
            name="created_by",
            field=models.ForeignKey(
                default="916b7cd9-26d2-40f0-a464-a912e353c3a9",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
