# Generated by Django 4.2.11 on 2024-06-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicants", "0012_applicants_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicants",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
