# Generated by Django 4.2.11 on 2024-04-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='applied_ROI',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='applied_loan_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='applied_tenure',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='case_tag',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='legal_and_incidental_fee',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='processing_fees',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='rcu_charges_applicable_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='stamp_duty_applicable_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='stamping_expenses_applicable_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='valuation_charges',
        ),
    ]
