# Generated by Django 4.2.11 on 2024-04-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='remark',
        ),
        migrations.AddField(
            model_name='loan',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_auth.comments'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='case_tag',
            field=models.CharField(choices=[('normal', 'Normal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='product_type',
            field=models.CharField(choices=[('normal', 'Normal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_type',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
    ]
