# Generated by Django 4.2.11 on 2024-04-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_remove_loan_remark_loan_comment_alter_loan_case_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='transaction_type',
            field=models.CharField(choices=[('automatic', 'Automatic')], default='automatic', max_length=255, null=True),
        ),
    ]
