# Generated by Django 4.2.11 on 2024-05-06 18:15

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
        ('applicants', '0009_alter_applicants_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caf_id', models.CharField(default=utils.generate_cafID, max_length=255, unique=True)),
                ('tentative_amt', models.FloatField(blank=True, max_length=15, null=True)),
                ('pdWith', models.CharField(blank=True, max_length=255, null=True)),
                ('placeOfPdAddress', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('applicant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_id', to='applicants.applicants')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_auth.comments')),
            ],
        ),
    ]
