# Generated by Django 4.2.11 on 2024-05-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customerdetails_customersegment'),
        ('caf_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafdetails',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetails'),
        ),
    ]
