# Generated by Django 4.2.11 on 2024-05-09 06:58

from django.db import migrations, models
import django.db.models.deletion
import utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0010_audittrail'),
        ('user_auth', '0001_initial'),
        ('customer', '0013_customeraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApplicationForm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caf_id', models.CharField(default=utils.generate_cafID, max_length=255, unique=True)),
                ('tentative_amt', models.FloatField(blank=True, max_length=15, null=True)),
                ('placeOfPdAddress', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('applicant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_id', to='applicants.applicants')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_auth.comments')),
                ('pdWith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
