# Generated by Django 4.2.11 on 2024-05-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('applicants', '0011_alter_applicants_description_alter_applicants_lead'),
        ('customer', '0014_alter_customerdetails_agriculturalland_and_more'),
        ('customer_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapplicationform',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_id', to='applicants.applicants'),
        ),
        migrations.AlterField(
            model_name='customerapplicationform',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_auth.comments'),
        ),
        migrations.AlterField(
            model_name='customerapplicationform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplicationform',
            name='pdWith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetails'),
        ),
    ]
