# Generated by Django 4.2.11 on 2024-04-23 17:06

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0006_alter_applicants_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_id', models.CharField(default=utils.generate_CollateralID, max_length=255, unique=True)),
                ('collateralType', models.CharField(max_length=255, null=True)),
                ('collateralName', models.CharField(max_length=255)),
                ('primarySecondary', models.CharField(max_length=255, null=True)),
                ('valuationRequired', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('relationshipWithLoan', models.CharField(max_length=255, null=True)),
                ('propertyOwner', models.CharField(max_length=255, null=True)),
                ('propertyCategory', models.CharField(max_length=255, null=True)),
                ('propertyType', models.CharField(max_length=255, null=True)),
                ('occupationStatus', models.CharField(max_length=255, null=True)),
                ('propertyStatus', models.CharField(max_length=255, null=True)),
                ('propertyTitle', models.CharField(max_length=255, null=True)),
                ('houseFlatShopNo', models.CharField(max_length=255, null=True)),
                ('khasraPlotNo', models.CharField(max_length=255, null=True)),
                ('locality', models.CharField(max_length=255, null=True)),
                ('village', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('taluka', models.CharField(max_length=255, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('landmark', models.CharField(max_length=255, null=True)),
                ('estimatedPropertyValue', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('documentName', models.CharField(max_length=255, null=True)),
                ('documentUpload', models.CharField(max_length=300, null=True)),
                ('remark', models.TextField(null=True)),
                ('isExisting', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Applicant_collateral', to='applicants.applicants')),
            ],
        ),
    ]
