# Generated by Django 4.2.11 on 2024-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_details', '0003_alter_collateraldetails_isexisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateraldetails',
            name='isExisting',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
