# Generated by Django 4.2.11 on 2024-05-02 07:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_details', '0004_alter_collateraldetails_isexisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateraldetails',
            name='id',
        ),
        migrations.AddField(
            model_name='collateraldetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collateraldetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collateraldetails',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
