# Generated by Django 4.2.11 on 2024-05-09 13:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collateral_details', '0005_alter_collateraldetails_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateraldetails',
            name='id',
        )
    ]
