# Generated by Django 4.2.11 on 2024-05-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_alter_applicants_status'),
        ('caf_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_caf',
            name='applicant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_id', to='applicants.applicants'),
        ),
    ]
