# Generated by Django 4.2.11 on 2024-05-02 07:24

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('caf_details', '0002_alter_customer_caf_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_caf',
            name='id',
        ),
        migrations.AddField(
            model_name='customer_caf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 2, 7, 8, 22, 290885, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_caf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer_caf',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
