# Generated by Django 4.2.11 on 2024-04-20 16:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_alter_leads_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=100)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leads.leads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentsUpload',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(max_length=255)),
                ('document_id', models.CharField(max_length=255, null=True)),
                ('file', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('kyc', 'KYC'), ('other', 'Other')], max_length=255)),
                ('kyc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kyc.kycdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
