# Generated by Django 4.2.11 on 2024-04-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leads.leads'),
        ),
        migrations.AddField(
            model_name='documentsupload',
            name='kyc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kyc.kycdetails'),
        ),
    ]
