# Generated by Django 4.2.11 on 2024-04-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_documentsupload_comment_documentsupload_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetails',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
