# Generated by Django 4.2.11 on 2024-05-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_leads_agent_code'),
        ('kyc', '0004_alter_kycdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='lead_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.leads'),
        ),
    ]
