# Generated by Django 4.2.11 on 2024-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_kycdetails_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='kyc_document_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycdetails',
            name='kyc_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
