# Generated by Django 4.2.11 on 2024-05-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('applicants', '0011_alter_applicants_description_alter_applicants_lead'),
        ('kyc', '0006_kycdetails_kyc_document_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsupload',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application', to='applicants.applicants'),
        ),
        migrations.AlterField(
            model_name='documentsupload',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_auth.comments'),
        ),
        migrations.AlterField(
            model_name='documentsupload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentsupload',
            name='document_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentsupload',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentsupload',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyc_details', to='kyc.kycdetails'),
        ),
        migrations.AlterField(
            model_name='kycdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
