# Generated by Django 4.2.11 on 2024-05-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_alter_documentsupload_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsupload',
            name='document_type',
            field=models.CharField(choices=[('kyc', 'KYC'), ('other', 'Other'), ('photos', 'Photos')], max_length=255),
        ),
    ]
