# Generated by Django 4.2.11 on 2024-06-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0008_alter_documentsupload_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsupload",
            name="file",
            field=models.CharField(),
        ),
    ]
