# Generated by Django 4.2.11 on 2024-04-23 09:15

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('phonepay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=utils.generate_PaymentID, max_length=255, unique=True),
        ),
    ]
