# Generated by Django 4.2.11 on 2024-05-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonepay', '0005_alter_payment_amount_alter_payment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Done', max_length=255),
        ),
    ]
